### ISSUE TITLE
Elite creatures never loot

### ISSUE THREAD

**Issue by tbayart** [mangostwo/server#60] opened 2014-03-27 09:10 UTC
When an Elite mob is killed, it never drop anything else than money.

Don't know if there is something broken in database, server ou mangos.conf file.
Maybe something missing.

**Comment by Necrovoice** [comment] 2017-01-18 02:27
Not enough information (2years old) Unable to reproduce.

**Comment by tbayart** [comment] 2017-01-27 09:40
It's been a while I didn't run my server. Need to upgrade to latest and try again.
In case this defect still there, what could I do to help you investigate ?

**Comment by billy1arm** [comment] 2017-01-27 11:31
@tbayart @Necrovoice - If you could, download the develop21 branch and build the server. I think the issue was fixed, but i'm not 100% sure.

iirc - this affected ALL Elite mobs ?

**Comment by billy1arm** [comment] 2017-02-16 18:01
@tbayart - The develop21 branch is now merged into master

**Comment by billy1arm** [comment] 2017-06-03 10:30
@Necrovoice - Did we ever get to the bottom of this ?

**Comment by Necrovoice** [comment] 2017-06-03 11:48
This can be closed

**Closed** 2017-06-03 14:28 UTC
